# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://lashford.info
title: Lashford.info
email: alexlashford@gmail.com
author: Alex Lashford
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2018 Lashford.info. All Rights Reserved.'
credits: 'Credits: ...'
baseurl: "/blog/" # the subpath of your site, e.g. /blog

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# Define number of posts per page
paginate: 2
paginate_path:  "/blogs/page:num/"

plugins:
  - jekyll-paginate

############################################################

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/lashford
  - title: github
    url: https://github.com/lashford
  - title: linkedin
    url: https://linkedin.com/profile/alex.lashford
