# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.lashford.info
title: Relative Engineering
subTitle: A collection of ramblings, thoughts & code snippets
email: alexlashford@gmail.com
author: Alex Lashford
description: > # "Write an awesome description for your new site here.
  Relative Engineering is the profile and technology blog of Alex Lashford, Engineer . Leader . Pragmatist.
copyright: 'Copyright &copy; 2018 Lashford.info.'
credits: 'Images from deathtothestockphoto.com'
#baseurl: "/" # the subpath of your site, e.g. /blog

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# Define number of posts per page
paginate: 4
paginate_path:  "/blogs/page:num/"

plugins:
  - jekyll-paginate

############################################################

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/alexlashford
  - title: github
    url: https://github.com/lashford
  - title: linkedin
    url: https://www.linkedin.com/in/alexlashford
